# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a69d960fc346d0fe603c5558e7043cd3d25617d8f013d7d562ee700894eeb3dd1eb0bbb370251505e62f275d15787182f06afd1b5bc261b5590329880af5c4

test:
  secret_key_base: 0f258588eeb2e20f1d8133950b5b693795a634a0aaca8778704bdc5ca489a6b8b71f062c317d18dc9e6efd1f6b65333f36c5213db2f9e7be980397ea4a09a92d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
